### ISSUE TITLE
Add `--color` to always color the output

### ISSUE THREAD

**Issue by o-jasper** [ofavre/vimcat#11]
It is a tool to colorize code, why deny/force workarounds for scripts.

Something like https://github.com/theZiz/aha could be used to produce colorized-with-HTML, for instance.

**Comment by o-jasper** [comment]
Looks like it might be too slow for my application, even with empty file at `-u`.. (0.5s)

It is nice to at least have a program that highlights just as the vim editor, even if it's not very fast, so still thanks for that!

**Comment by ofavre** [comment]
Hi @o-jasper,

The program slowness was starting to annoy me too so I addressed it.
45ed31b brings massive speed improvements.
Can you please check with the latest code from master? I did not create new packages since the first release eons ago.

I do not understand your first comment though, because I've just checked that piping vimcat's output, through cat for instance, will not change colorization.
There is no feature deactivated when the output is not a TTY. At least as of the last code, maybe that was the case with earlier versions. Or maybe that's due to a configuration on your side?
